### ISSUE TITLE
Typo in hobbies section

### ISSUE THREAD

**Issue by tarikkirgin** [othyn/othyn.com#8]
Unless this is skiing terminology unbeknownst to me, I imagine this should say 'gear' instead of 'hear' :)

https://github.com/othyn/othyn.com/blob/5680416bd29460635d9d4e2d5aa8a869578345fe/components/sections/home/Hobbies.vue#L20

**Comment by othyn** [comment]
Thank you! 😄 might have been the helmet getting in the way haha
